# Build / Serve stage for Nginx
FROM nginx:alpine

# Copy custom Nginx proxy configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static HTML/JS files to Nginx web root
COPY . /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]